FEEL variable scope resolution
bpmn-io/variable-resolver pull request #43
Opened 2024-12-16 18:23 UTC by abdul99ahad

Related to: [camunda-modeler #4737](https://github.com/camunda/camunda-modeler/issues/4737)

### Proposed Changes

 
When script result variable and input with same names coexist, result variable overwrites the input variable.
![Dec-16-2024 23-19-02](https://github.com/user-attachments/assets/0479cc4c-c109-4880-8957-0b76c6cc6abb)

When same name input/output mapping exists, the later one overwrites the previous one.
![Dec-16-2024 23-19-50](https://github.com/user-attachments/assets/05991e67-01fe-4b15-a961-3a6d8e3d2bc7)

### Checklist

To ensure you provided everything we need to look at your PR:

* [ ] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

2024-12-16 18:24 UTC, abdul99ahad commented
Requires fixed-upstream: https://github.com/bpmn-io/extract-process-variables/pull/30

2025-01-02 08:06 UTC, nikku commented
Upstream fix [released](https://github.com/bpmn-io/extract-process-variables/pull/30#issuecomment-2567393596), this can be moved further.

2025-01-07 16:17 UTC, nikku commented on lib/zeebe/util/feelUtility.js
> -  const mapping = mappings.find(mapping => mapping.target === variable.name);
I'd apprechiate if we'd group the fix with the actual test that verifies the fix. This way it is easier to understand what we fixed.

2025-01-07 16:22 UTC, nikku commented on lib/zeebe/VariableResolver.js
> +    const uniqueVariables = new Map();
This can be simplified in some ways (I think):

```
// use min-dash uniqueBy utility
const uniqueVariables = uniqueBy('name', filteredVariables.reverse());
```

```
const uniqueVariables = Object.values(
  filteredVariables.reduce((uniqueVariables, v) =>  {
    uniqueVariables[v.name] = v;
    return uniqueVariables;
  })
);
```

Maybe it even makes sense to do the filtering in the previous block?

2025-01-07 16:41 UTC, abdul99ahad commented on lib/zeebe/util/feelUtility.js
> -  const mapping = mappings.find(mapping => mapping.target === variable.name);
This fix corresponds to 
> When multiple input or output variables with same name exists within the same process/activity, the later one overwrites all the previous ones.

I'll see if the test case doesn't exist for this, I'll add one. Thanks for pointing this out.

2025-01-07 18:46 UTC, nikku commented on lib/zeebe/util/feelUtility.js
> -  const mapping = mappings.find(mapping => mapping.target === variable.name);
We could also search mappings from last to first: 

```
mappings.reverse().find(...);
```

2025-01-08 10:17 UTC, abdul99ahad commented on lib/zeebe/util/feelUtility.js
> -  const mapping = mappings.find(mapping => mapping.target === variable.name);
Is there any particular reason we're sticking to find(...) and avoid filter(...).pop() ?

2025-01-08 10:34 UTC, abdul99ahad commented on lib/zeebe/VariableResolver.js
> +    const uniqueVariables = new Map();
Implemented. The variables are now filtered distinctly using uniqueBy from `min-dash` in the base VariableResolver.

2025-01-08 12:07 UTC, nikku requested changes

2025-01-08 12:07 UTC, nikku commented on lib/zeebe/util/feelUtility.js
> -  const mapping = mappings.find(mapping => mapping.target === variable.name);
Find aborts early, while filter goes through the whole list. But in the end it is a matter of taste.

`pop()` is also not side-effect free, so it is not fully functional, and may cause (in some situations) issues.

2025-01-08 12:09 UTC, nikku commented on lib/zeebe/VariableResolver.js
> +    const namesToFilter = getElementNamesToRemove(moddleElement, inputOutput);
Same with other commit in this PR, what problem does this fix solve? I'd apprechiate if we'd pack implementation + test case together.

2025-01-08 12:10 UTC, nikku reviewed
@abdul99ahad Thanks for doing this additional round. I still find it a little bit hard to review your PR, because some "FIX" commits still don't contain tests for the actual bugs fixed.

For any reasonably complex topic (such as this one) we need rigid test coverage. I advice you to adopt the practice to pack fix + test into _one_ commit. This helps reviewers to trace what you were doing, and what exactly the expected effect is.

2025-01-08 13:32 UTC, abdul99ahad commented on lib/zeebe/VariableResolver.js
> +    const namesToFilter = getElementNamesToRemove(moddleElement, inputOutput);
This isn't a fix, just a refactor to clean up the code into a separate function. I'll make sure the commits are clear for reviewers.

2025-01-08 13:58 UTC, abdul99ahad commented
> @abdul99ahad Thanks for doing this additional round. I still find it a little bit hard to review your PR, because some "FIX" commits still don't contain tests for the actual bugs fixed.
> 
> I advice you to adopt the practice to pack fix + test into _one_ commit. This helps reviewers to trace what you were doing, and what exactly the expected effect is.

Thanks for pointing this out, Nico. I’ll make sure to include tests alongside fixes in a single commit for better traceability in the future. For now, I’ve separated the refactor into its own commit to keep things clearer.

2025-01-09 09:17 UTC, nikku commented
Ok, I'll see what I can do, and update this PR with co-location. Will ping you to check back with you, if I grouped things appropriately.

2025-01-11 14:36 UTC, abdul99ahad commented
> Ok, I'll see what I can do, and update this PR with co-location. Will ping you to check back with you, if I grouped things appropriately.

I have grouped the fixes and tests. 🏅

2025-01-15 09:29 UTC, nikku commented
@philippfromme Can you take over my review on this?

2025-01-15 10:03 UTC, philippfromme commented
Will do.

2025-01-15 13:55 UTC, philippfromme commented on lib/base/VariableResolver.js
> +    const uniqueVariables = uniqueBy('name',allVariables.reverse());
This seems to correspond to

> When multiple input or output variables with same name exists within the same process/activity, the later one overwrites all the previous ones.

This concern doesn't seem to be tested anywhere specifically.

2025-01-15 14:02 UTC, abdul99ahad commented on lib/base/VariableResolver.js
> +    const uniqueVariables = uniqueBy('name',allVariables.reverse());
This one is for 
> Result variable and input have same names, result variable will be available throughout overwriting input variable.
 Result variable and output have same names, output variable will be available overwriting result variable.
 Input and output have same names, output variable name will overwrite the input variable.
 
The one you mentioned corresponds to test `should only resolve the latest variable if same name input/output exists` in separate commit.
> When multiple input or output variables with same name exists within the same process/activity, the later one overwrites all the previous ones.

2025-01-20 12:51 UTC, philippfromme commented on test/fixtures/zeebe/mappings/scope.bpmn
> -<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http:
This commit contains a lot of changes to the XML with no corresponding tests. Furthermore, some of the elements you added don't seem to be used in any tests later on (e.g. `Participant_2`) please help me out here and ensure that every commit bundles the tests and the changes to the XML that are necessary.

2025-01-20 19:57 UTC, abdul99ahad commented on test/fixtures/zeebe/mappings/scope.bpmn
> -<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http:
I have combined xml commits with respective fixes and tests.

2025-01-23 12:28 UTC, merged